baseURL: 'https://www.liuchang0812.com/'
languageCode: zh-cn
title: 读书与编程
theme: PaperMod
enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  social: true
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: false
  DateFormat: "2006-01-02"
  env: production
  
  profileMode:
    enabled: false
    title: ​Tech and Text Tales
    subtitle: "I'm Liu Chang, a programmer. This blog mainly focuses on sharing technical experiences and insights, and I will also share some excellent books I've read from time to time. Welcome to follow and communicate."

    buttons:
      - name: 👨🏻‍💻文章
        url: posts
      - name: 🙋🏻‍♂️关于
        url: about
        
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 1
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary"]      

  cdn:
    enable: true
    # Host must NOT end with `/`
    Host: "https://cdn.jsdelivr.net/gh/liuchang0812/liuchang0812.github.io/content"

markup:
  highlight:
        codeFences: true  
        guessSyntax: true
        lineNos: false
        style: darcula
    
menu:
  main:
    - name: 🙋🏻‍♂️关于
      url: /about/
      weight: 4
      
    - name: ⏱时间轴
      url: /archives/
      weight: 3
      
    - name: 🔍搜索
      url: /search/
      weight: 2
      
    - identifier: posts
      name: 📚文章
      url: posts
      weight: 1
